import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({
    weight: ['400','500','600', '700'],
    style: ['normal'],
    subsets: ['latin'],
    display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
